version: '2'

services:
  apache:
    build:
      context: .
      dockerfile: e2e_test/docker/apache/Dockerfile
    expose:
      - "80"
    networks:
      - default
    container_name: apache
    privileged: true
  abmruby:
    build:
      context: .
      dockerfile: e2e_test/docker/ab_mruby/Dockerfile
    links:
      - apache
    networks:
      - default
    container_name: abmruby
networks:
  default:
